name: siaga_darah
description: A blood donation app for Indonesia.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.4
  device_preview: ^1.2.0
  stylish_bottom_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets yang diperlukan
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icon/

  # Fonts (optional - menggunakan system font)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
