// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsB_MltL8b9Lt6tAAvVfThYm1G8vVcWu0',
    appId: '1:461565299357:web:da2b289ffd6908423f6274',
    messagingSenderId: '461565299357',
    projectId: 'siagadarah',
    authDomain: 'siagadarah.firebaseapp.com',
    storageBucket: 'siagadarah.firebasestorage.app',
    measurementId: 'G-MLGPQ47VPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNuIDx7FUcyfrGBgkMy0x8px2G6ZNcD0',
    appId: '1:461565299357:android:b8b80f5aca0ec1033f6274',
    messagingSenderId: '461565299357',
    projectId: 'siagadarah',
    storageBucket: 'siagadarah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcTLiVftvOvwi8E_34teEzDq9wtBtVryI',
    appId: '1:461565299357:ios:9a6f39b0639d207a3f6274',
    messagingSenderId: '461565299357',
    projectId: 'siagadarah',
    storageBucket: 'siagadarah.firebasestorage.app',
    iosBundleId: 'com.example.siagaDarah',
  );
}
